### PR TITLE
fix: update instead of recreate tooltips, and more.

### PR DESCRIPTION
**Pull request by carlank**
Hey! I wouldn't necessarily recommend that you just accept this and merge it, as I enforced a style (called Prettier) on `idle_game.js`, but this is how I would do the tooltip updating.

I also included some other small fixes around the way that are general good practices.

One larger thing I noticed, you might want to "transpose" your objects; i.e. instead of having
```js
building = {
  name: [list of names],
  image: [list of images],
  ...
}
```
you could consider
```js
buildings = [
  {
    name: "Old Couch",
    image: "oldcouch.png",
    count: 0,
    baseIncome: 1,
    ...
  },
  {
   name: "Cracked IV",
   image: "crackedtv.png",
   ...
 },
 ...
]
```

It's a bit more duplication, since you have to rewrite the field names for each object, but it's a much more flexible system that'll be easier to update! Eventually, you could make the buildings/upgrades/etc. classes, and give them default values and other things like that once you get that far!

### CODE REVIEW

**Comment by carlank** [comment]
Oh, I would make sure to review this commit by commit instead of all at once, since the style change basically changed a ton

**Comment by BernbarkProfessional** [comment]
Hey,

This is awesome, thank you! I am going to spend some time looking over how
to properly pull this because I have a lot of content added to the project
before I noticed your pull request. Some of the things I tried to fix, such
as tooltip updating, I was having a hard time with but eventually got
working in not such a great way, but I tried to do it by caching to arrays
as in your example and it wasn't working properly for me for some reason.

I've never had a chance to collaborate with strangers before so this is
kinda neat.

Btw, are you the person that has been helping me in the comments on Reddit
broken mouse convention?

Thanks again!

**Comment by carlank** [comment]
Hah, forgot I have a different username. Yeah, same person! Glad to help!

Because these changes are so large (mainly the formatting), it's not that straightforward to combine them. In a normal situation, you would want to just merge them manually or ask me to rebase my fork against main and then do the merge, but that's not helpful here. Since you're learning, I would actually totally recommend just recreating them yourself, but hopefully these are good examples!

I was messing around with it and accidentally triggered your build system to merge and close the PR :P, I reopened a new one for simplicity.

**Comment by BernbarkProfessional** [comment]
Hey man this is awesome. I've definitely been studying what you've shown me
so far. Always glad to get some real experience to show me what I'm doing
right or wrong.

Thanks again, I will try to merge these manually in the next few days!

**Pull request merged**
